[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
via_ir = true
optimizer = true
optimizer_runs = 999
ffi = true
names = true
sizes = true
gas_reports = [
    "AccountFactory", 
    "K1ValidatorFactory",
    "MetaFactory", 
    "ModuleFactory", 
    "RegistryFactory", 
    "Vortex"
]
fs_permissions = [
    { access = "read", path = "config"},
    { access = "read", path = "out"}
]

[rpc_endpoints]
ethereum = "${ETHEREUM_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
optimism-sepolia = "${OPTIMISM_SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
polygon-amoy = "${POLYGON_AMOY_RPC_URL}"
base = "${BASE_RPC_URL}"
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
arbitrum-sepolia = "${ARBITRUM_SEPOLIA_RPC_URL}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_ETHEREUM}" }
sepolia = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_SEPOLIA}" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "${ETHERSCAN_URL_OPTIMISM}" }
optimism-sepolia = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "${ETHERSCAN_URL_OPTIMISM_SEPOLIA}" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", url = "${ETHERSCAN_URL_POLYGON}" }
polygon-amoy = { key = "${ETHERSCAN_API_KEY_POLYGON}", url = "${ETHERSCAN_URL_POLYGON_AMOY}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}", url = "${ETHERSCAN_URL_BASE}" }
base-sepolia = { key = "${ETHERSCAN_API_KEY_BASE}", url = "${ETHERSCAN_URL_BASE_SEPOLIA}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_URL_ARBITRUM}" }
arbitrum-sepolia = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_URL_ARBITRUM_SEPOLIA}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
