[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false
via_ir = true
optimizer = true
optimizer_runs = 200
names = true
sizes = true
gas_reports = ["AccountFactory", "MetaFactory", "RegistryFactory", "VortexFactory", "Vortex"]
fs_permissions = [
    { access = "read", path = "config/"},
    { access = "read", path = "out/"},
    { access = "read", path = "script/"}
]

[rpc_endpoints]
ethereum = "${RPC_ETHEREUM}"
sepolia = "${RPC_SEPOLIA}"
optimism = "${RPC_OPTIMISM}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
base = "${RPC_BASE}"

[etherscan]
ethereum = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_ETHEREUM}" }
sepolia = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_SEPOLIA}" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "${ETHERSCAN_URL_OPTIMISM}" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", url = "${ETHERSCAN_URL_POLYGON}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_URL_ARBITRUM}" }
base = { key = "${ETHERSCAN_API_KEY_BASE}", url = "${ETHERSCAN_URL_BASE}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
